service: nanlabs-trello
variablesResolutionMode: 20210326
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

custom:
  secrets:
    trello: ${ssm:/aws/reference/secretsmanager/trello}

functions:
  createCard:
    handler: src/cards/handler.createCardHandler
    environment:
      TRELLO_API_KEY: ${self:custom.secrets.trello.trelloAPIKey}
      TRELLO_API_CLIENT_TOKEN: ${self:custom.secrets.trello.trelloAPIClientToken}
    events:
      - httpApi:
          path: /
          method: post
