service: nanlabs-trello
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

functions:
  createCard:
    handler: src/cards/handler.createCardHandler
    events:
      - httpApi:
          path: /
          method: post
