service: nanlabs-trello
variablesResolutionMode: 20210326
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, 'dev'}

custom:
  config: ${file(config/${self:provider.stage}.json)}
  secrets:
    trello: ${ssm:/aws/reference/secretsmanager/trello}

functions:
  createCard:
    handler: src/cards/handler.createCardHandler
    environment:
      # Keys
      TRELLO_API_KEY: ${self:custom.secrets.trello.trelloAPIKey}
      TRELLO_API_CLIENT_TOKEN: ${self:custom.secrets.trello.trelloAPIClientToken}
      # URLs
      TRELLO_BASEPATH: ${self:custom.config.trello.baseURL}
      TRELLO_CARDS: ${self:custom.config.trello.cards}
    events:
      - httpApi:
          path: /
          method: post
